# .golangci.yml

run:
  timeout: 5m

linters:
  disable:
    - goanalysis_metalinter
    - govet
    - staticcheck
    - unused
    - typecheck

  enable:
    - errcheck
    - gosimple
    - ineffassign
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Printf
